name: 新功能建议
description: 为网站提供一些好的想法。
title: "[Feature]: "
labels: ["类型:需求"]
# projects: ["octo-org/1", "octo-org/44"]
assignees:
  - QingFeng-awa
body:
  - type: markdown
    attributes:
      value: |
        感谢您愿意花费时间来为TONEX官方网站贡献想法。<br>
        XtremeWaveWebSite(XWS)欢迎您提出自己的想法。
  - type: input
    id: Email
    attributes:
      label: 联系方式(邮箱)
      description: 接受市面上大部分的邮箱,我们推荐您使用@163.com/@qq.com。您可以选择不填。
    validations:
      required: false
  - type: textarea
    id: main
    attributes:
      label: 新功能的详细描述是什么?
    validations:
      required: true
  - type: textarea
    id: programme
    attributes:
      label: 此功能的实现思路是什么?
      description: 请您描述的详细一点。
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: 其它信息
    validations:
      required: false
